# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default=0, max_length=50)),
                ('sub_category', models.TextField(default=0, max_length=50)),
                ('start_time', models.DateTimeField(default=0)),
                ('end_time', models.DateTimeField(default=0)),
                ('student', models.TextField(default=0, max_length=50)),
                ('phone_number', models.IntegerField(default=0)),
                ('enrollment_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
